### ISSUE TITLE
Instrumentation cannot find package.json on startup

### ISSUE THREAD

**Issue by maxdeichmann** [appsignal/opentelemetry-instrumentation-bullmq#7]
I am using this package in a dockerized Nextjs application. When i try to run the application, i get the error below. Is this something you encountered already?

Context:

- [package.json](https://github.com/langfuse/langfuse/blob/27833184c033faddca1bf561dc9ae639da4855f9/web/package.json#L24-L25) with my dependencies
- [instrumentation](https://github.com/langfuse/langfuse/blob/27833184c033faddca1bf561dc9ae639da4855f9/web/src/instrumentation.ts#L3) file from nextjs
- [Instrumentation setup](https://github.com/langfuse/langfuse/blob/27833184c033faddca1bf561dc9ae639da4855f9/web/src/datadog.server.config.ts#L1)

```
web:dev: Error: An error occurred while loading instrumentation hook: Cannot find module '/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/package.json'
web:dev:     at webpackEmptyContext (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/_instrument_node_modules_pnpm_appsignal_opentelemetry-instrumentation-bullmq_0_7_1_bullmq_5_4-44d1a0.js:20:10)
web:dev:     at eval (webpack-internal:///(instrument)/../node_modules/.pnpm/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3/node_modules/@appsignal/opentelemetry-instrumentation-bullmq/dist/version.js:11:222)
web:dev:     at (instrument)/../node_modules/.pnpm/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3/node_modules/@appsignal/opentelemetry-instrumentation-bullmq/dist/version.js (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/vendor-chunks/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3.js:42:1)
web:dev:     at __webpack_require__ (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at eval (webpack-internal:///(instrument)/../node_modules/.pnpm/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3/node_modules/@appsignal/opentelemetry-instrumentation-bullmq/dist/instrumentation.js:22:19)
web:dev:     at (instrument)/../node_modules/.pnpm/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3/node_modules/@appsignal/opentelemetry-instrumentation-bullmq/dist/instrumentation.js (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/vendor-chunks/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3.js:52:1)
web:dev:     at __webpack_require__ (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at eval (webpack-internal:///(instrument)/../node_modules/.pnpm/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3/node_modules/@appsignal/opentelemetry-instrumentation-bullmq/dist/index.js:4:25)
web:dev:     at (instrument)/../node_modules/.pnpm/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3/node_modules/@appsignal/opentelemetry-instrumentation-bullmq/dist/index.js (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/vendor-chunks/@appsignal+opentelemetry-instrumentation-bullmq@0.7.1_bullmq@5.4.3.js:31:1)
web:dev:     at __webpack_require__ (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at eval (webpack-internal:///(instrument)/./src/datadog.server.config.ts:14:105)
web:dev:     at (instrument)/./src/datadog.server.config.ts (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/_instrument_node_modules_pnpm_appsignal_opentelemetry-instrumentation-bullmq_0_7_1_bullmq_5_4-44d1a0.js:142:1)
web:dev:     at Function.__webpack_require__ (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at async Module.register (webpack-internal:///(instrument)/./src/instrumentation.ts:15:9)
web:dev:     at async DevServer.runInstrumentationHookIfAvailable (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/server/dev/next-dev-server.js:437:17)
web:dev:     at async Span.traceAsyncFn (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/trace/trace.js:154:20)
web:dev:     at async DevServer.prepareImpl (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/server/dev/next-dev-server.js:214:9)
web:dev:     at async NextServer.prepare (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/server/next.js:161:13)
web:dev:     at async initializeImpl (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/server/lib/render-server.js:98:5)
web:dev:     at async initialize (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/server/lib/router-server.js:423:22)
web:dev:     at async Server.<anonymous> (/Users/maximiliandeichmann/development/github.com/langfuse/langfuse/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/server/lib/start-server.js:249:36) {
web:dev:   code: 'MODULE_NOT_FOUND'
web:dev: }
```

**Comment by unflxw** [comment]
Hi @maxdeichmann @Steffen911,

Thank you for reporting this issue, and apologies for the delay in getting back to you.

Could you provide a repository with a sample application that reproduces the issue? That would be, for example, a freshly initialized Next.js application that uses this instrumentation with a standard OpenTelemetry setup.

Could you also try adding `@appsignal/opentelemetry-instrumentation-bullmq` to [the `serverExternalPackages` Next.js configuration option](https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages)? This seems like it could be an issue with Webpack bundling.

**Comment by Steffen911** [comment]
@unflxw Thank you for the response. I just tested your suggestion and can confirm that the initialization succeeds if I include the bullmq instrumentation in `serverComponentsExternalPackages`.

**Comment by unflxw** [comment]
Interesting, thank you for reporting back @Steffen911. I'm unsure why that would be necessary, but nonetheless it's good to know there's a workaround.

**Comment by iwalt** [comment]
I've ran into the same issue using esbuild; there's no _package.json_ where [this line here](https://github.com/appsignal/opentelemetry-instrumentation-bullmq/blob/7d2d431767bc2cbb7e85bf51d13f9fd257a2e655/src/version.ts#L5) is looking for it.

I can see that this `VERSION` is only really used as the `instrumentationVersion` passed to [InstrumentationBase](https://open-telemetry.github.io/opentelemetry-js/classes/_opentelemetry_instrumentation.InstrumentationBase.html). I believe this should be the version of `@appsignal/opentelemetry-instrumentation-bullmq` rather than the version of my instrumented application. Would you accept a PR to this effect?

**Comment by unflxw** [comment]
@iwalt Yes, that's correct -- it should be the version of the instrumentation, not that of the application it instruments. Thank you for pointing out this issue! Please feel free to submit a PR to fix that.
